version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
